version: '3'

services:
  app.api:
    image: ghcr.io/libertech-fr/app.api:latest
    container_name: ${APP_NAME:-app.api}
    restart: unless-stopped
    env_file: ./volumes/ui/.env
    ports:
      - "${APP_PORT:-4545}:4545"
