version: '3'

services:
  app.ui:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    container_name: ${APP_NAME:-app.ui}
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./:/data
    networks: ['dev']
    environment:
      - NODE_ENV=development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: yarn dev

networks:
  dev:
    external: true
